In [18]:
import numpy, json, os, fvecs
config_path = "/media/gtnetuser/SSD_2TB_ALICE/distribution_new/ann-codes/in-memory/EXPERIMENTS/siftN/config/knnkdei_v1.json"
with open(config_path) as fin:
    config = json.load(fin)



In [19]:
knn_data = fvecs.ivecs_read(config["knn filename"])
kde_data = fvecs.fvecs_read(config["kde filename"])
knn_data.shape, kde_data.shape

((1000, 100), (1000, 1))

In [22]:
knn_gt = fvecs.ivecs_read("/media/gtnetuser/SSD_2TB_ALICE/distribution_new/ann-codes/in-memory/EXPERIMENTS/siftN/gt.ivecs")
knn_gt[:, :100]

array([[9473202, 5995891,  209761, ..., 9662729, 2307243,  201789],
       [1547731, 5101660, 8807600, ..., 8638280, 4643355, 3790884],
       [5400783, 2375692, 2786483, ..., 5201206, 2330600, 2927383],
       ...,
       [4294544, 8860619, 9547464, ..., 9932868,  909708, 1543077],
       [3708574, 8694776, 5115208, ..., 4964730, 9037679, 9612541],
       [3110870, 5029183, 8871438, ..., 5394953, 2768747, 2173207]],
      dtype=int32)

In [23]:
knn_data[0]

array([9473202, 5995891, 5068948, 7192838, 7825526, 1112776, 7078876,
       5289129, 5667498, 1339024, 3471877, 4614166, 2960275, 8988475,
       1574673, 1353641, 2730637,  466104, 2002224, 1954216, 6193096,
       8725377, 2026997, 8701211, 4332438, 5262574, 9329539, 4316839,
       2328039, 1804027, 7077745,  139655, 1574218, 4394732, 8188782,
       9500671, 5823213, 4262716, 1223066, 7094673, 9249059, 9763690,
       6338478, 8921285,  774269, 6797090, 7400232, 6369584, 4347992,
       2845718, 8004112, 2307243, 6821197, 1290119, 1590547, 8817169,
       8924290,  220821, 9267129, 5908142, 8596932, 1830568, 7907221,
       2109395, 4811695, 4729448, 6150584, 9058549, 5237633,   68919,
       4046216, 5430642, 3976178, 4913727, 7656905, 7137497, 4722345,
        917852, 6881692, 1076514, 5858067, 6770278, 2248609, 6749564,
       7520486, 2669848, 3933965, 5142216, 3671463, 9058885, 7999603,
       4138409, 3878928, 3564373, 8212453, 8774472,  769648, 6490229,
       3228132, 7282

In [13]:
knn_gt[2][:100]

array([ 1150, 42136, 45739, 16694, 27368, 16056, 17601, 13169, 28628,
        7406, 51446, 51381, 17232, 39473,   437, 40862, 20130,  8264,
       30210, 41140, 41154,  7392, 52127, 24684, 50836, 39008,  3094,
       22502, 24238, 17239, 32263, 10274, 18593, 49801, 21141, 20035,
       10460, 13552, 47538, 18402,  9116, 31021, 20168, 52515, 48948,
         402, 21377, 17508, 14123, 28489, 12715, 51891, 39551, 18851,
        1523,  6831, 25360, 51492,  3526, 30567,  5456, 28366, 46334,
       15759, 17713, 49965,  7700, 35701, 14839, 25664, 24121, 23784,
       21162, 44776, 30875, 18081, 48898, 49282, 47042, 38007, 35716,
       22330, 31603, 44251, 23865, 14193, 23185,  3554, 28855, 13498,
       52549, 17470, 19524, 24059, 48858, 31581, 18448, 29603, 38214,
       38692], dtype=int32)

In [24]:
qn, n = knn_gt.shape
sum = 0
for i in range(qn):
    knn = set(knn_data[i])
    gt = set(knn_gt[i][:100])
    sum += len(knn.intersection(gt))
sum


81581

In [25]:
kde_gt = fvecs.dvecs_read(config["ground truth file"])
kde_gt[9]

array([6.40124380e-01, 7.12340705e-01, 9.12624930e+00, 3.37014519e+03,
       1.28428865e-01, 2.82288956e+03, 3.70213527e+02, 1.21817621e-01,
       2.63919910e+01, 4.22876484e+00, 9.70064114e-02, 1.56576965e+00,
       2.35751623e-02, 3.45270970e-01, 1.24495770e+02, 2.68966149e-02,
       5.51058967e+00, 2.06423383e-01, 9.01035925e+01, 5.93241644e-01,
       6.93369744e-02, 8.24413864e-01, 7.66448487e-01, 1.00444364e-02,
       2.32527765e-01, 4.09272810e+00, 3.16388543e-01, 6.00852474e+00,
       2.46339283e-01, 7.10288692e-02, 1.42071781e+00, 7.05459101e+00,
       8.45144615e+00, 3.48378981e-01, 4.62022752e-01, 2.36680816e-01,
       2.45853561e-01, 4.05022689e+00, 3.30064721e+00, 2.11445087e+00,
       3.38875765e+02, 2.80605889e+02, 3.19882027e-01, 1.47383164e+00,
       1.92938437e+01, 8.33591545e+01, 1.43083748e+00, 1.31861927e+01,
       4.38709847e-01, 6.06533481e-02, 1.52615116e+04, 1.58086036e+02,
       5.97274802e-02, 8.80977530e+01, 2.83101270e+01, 4.82333448e+00,
      

In [26]:
kde_data

array([[6.28401875e-01],
       [7.74466932e-01],
       [8.33709431e+00],
       [3.36246924e+03],
       [1.26099169e-01],
       [2.83038550e+03],
       [3.76796661e+02],
       [1.15898713e-01],
       [2.64080849e+01],
       [4.51137352e+00],
       [9.02213678e-02],
       [1.57147467e+00],
       [2.30823848e-02],
       [3.46168071e-01],
       [1.22227867e+02],
       [2.88699213e-02],
       [5.36470079e+00],
       [2.11729154e-01],
       [8.95747528e+01],
       [5.88331461e-01],
       [6.93389028e-02],
       [8.24359596e-01],
       [7.66741574e-01],
       [1.15063097e-02],
       [2.30595812e-01],
       [4.13160133e+00],
       [3.14406544e-01],
       [6.35863113e+00],
       [2.39353076e-01],
       [7.44039789e-02],
       [1.41116488e+00],
       [6.91933489e+00],
       [8.84742546e+00],
       [3.51233780e-01],
       [4.97328311e-01],
       [2.27042958e-01],
       [2.50150561e-01],
       [3.83636570e+00],
       [3.29401350e+00],
       [2.13261104e+00],


In [34]:
import numpy as np
mre = np.divide(np.abs(kde_data.transpose() - kde_gt[9]), kde_gt[9])
np.abs(kde_data.transpose() - kde_gt[9]).shape, kde_gt[9].shape, mre

((1, 1000),
 (1000,),
 array([[1.83128539e-02, 8.72142033e-02, 8.64709004e-02, 2.27763175e-03,
         1.81399682e-02, 2.65541233e-03, 1.77819943e-02, 4.85882673e-02,
         6.09801801e-04, 6.68300764e-02, 6.99442807e-02, 3.64358801e-03,
         2.09024005e-02, 2.59825165e-03, 1.82167078e-02, 7.33663484e-02,
         2.64742760e-02, 2.57033428e-02, 5.86924066e-03, 8.27686888e-03,
         2.78119384e-05, 6.58262817e-05, 3.82395340e-04, 1.45540600e-01,
         8.30848143e-03, 9.49812198e-03, 6.26444494e-03, 5.82682786e-02,
         2.83601043e-02, 4.75174358e-02, 6.72401367e-03, 1.91727807e-02,
         4.68534378e-02, 8.19452249e-03, 7.64151971e-02, 4.07209100e-02,
         1.74778858e-02, 5.28022732e-02, 2.00982076e-03, 8.58859667e-03,
         5.51471277e-03, 6.29396459e-04, 7.60385877e-03, 1.09967459e-02,
         1.32876594e-02, 7.30812092e-03, 1.59952137e-02, 8.98213553e-02,
         7.01899735e-02, 3.00776085e-02, 1.71808314e-03, 1.80993800e-02,
         2.03149846e-02, 5.20

In [35]:
np.mean(mre)

0.03595388006089937