In [22]:
from oniakIO import odats
import pathlib
import numpy as np

path = "/media/gtnetuser/SSD_2TB_ALICE/distribution_new/ann-codes/in-memory/EXPERIMENTS/glove/summary"
path = pathlib.Path(path)


In [62]:
knn_gt = odats.read_file(str(path/"../gt.ivecs"))
gt100 = knn_gt[:, :100]
gt1000 = knn_gt[:, :1000]
gt10000 = knn_gt[:, :10000]

In [63]:
k100p = odats.read_file(str(path / "rcl_kde_k100_precompute.fvecs"))
k1000p = odats.read_file(str(path / "rcl_kde_k1000_precompute.fvecs"))
k10000p = odats.read_file(str(path / "rcl_kde_k10000_precompute.fvecs"))
k100p.mean(), k1000p.mean(), k10000p.mean()

(0.794651, 0.7329774, 0.6532569)

In [64]:
k100pc = odats.read_file(str(path / "rcl_knn_k100_precompute.ivecs"))
k1000pc = odats.read_file(str(path / "rcl_knn_k1000_precompute.ivecs"))
k10000pc = odats.read_file(str(path / "rcl_knn_k10000_precompute.ivecs"))
k100ac = odats.read_file(str(path / "rcl_knn_k100_associative.ivecs"))
k100pc, k100ac

(array([[ 431504,   75780,   23267, ..., 1176064,  345587,  959687],
        [1090792,  638707,  554164, ...,  408744,  671067,  479806],
        [ 287570,  973468,  979442, ...,  219774,  492597, 1175301],
        ...,
        [ 153056,  408756, 1033865, ...,  914448,  745029, 1106092],
        [ 791306,  904295,  211727, ...,  660512,  425003, 1105355],
        [ 518761,  210678, 1100410, ...,  136544,  894887, 1060690]],
       dtype=int32),
 array([[ 431504,   75780,   23267, ..., 1176064,  345587,  959687],
        [1090792,  638707,  554164, ...,  408744,  671067,  479806],
        [ 287570,  973468,  979442, ...,  219774,  492597, 1175301],
        ...,
        [ 153056,  408756, 1033865, ...,  914448,  745029, 1106092],
        [ 791306,  904295,  211727, ...,  660512,  425003, 1105355],
        [ 518761,  210678, 1100410, ...,  136544,  894887, 1060690]],
       dtype=int32))

In [32]:
def avg_recall(gt, res):
    qn = gt.shape[0]
    recalls = np.zeros(qn)
    for i in range(qn):
        gnd = set(gt[i])
        result = set(res[i])
        recalls[i] = len(gnd.intersection(result)) / len(gnd)
    return recalls

In [66]:
k100a = odats.read_file(str(path / "rcl_kde_k100_associative.fvecs"))
k1000a = odats.read_file(str(path / "rcl_kde_k1000_associative.fvecs"))
k10000a = odats.read_file(str(path / "rcl_kde_k10000_associative.fvecs"))
k100a.mean(), k1000a.mean(), k10000a.mean()

(0.7603903, 0.70396054, 0.6430141)

In [20]:
k100p

array([[0.97714925],
       [0.04990912],
       [0.9430629 ],
       [0.8162254 ],
       [0.9943931 ],
       [0.85098034],
       [0.8063773 ],
       [0.6080246 ],
       [0.69555   ],
       [0.87039506],
       [0.8450147 ],
       [0.56044394],
       [0.9860614 ],
       [0.35463497],
       [0.800185  ],
       [0.9829518 ],
       [0.9971638 ],
       [0.92735523],
       [0.9046578 ],
       [0.61802953],
       [0.94052255],
       [0.8791333 ],
       [0.74397737],
       [0.95680124],
       [0.7514745 ],
       [0.9785243 ],
       [0.81873655],
       [0.39582446],
       [0.9403861 ],
       [0.98530334],
       [0.7238364 ],
       [0.9997988 ],
       [0.6042074 ],
       [0.9148224 ],
       [0.16168953],
       [0.9479775 ],
       [0.6583265 ],
       [0.86067355],
       [0.5558381 ],
       [0.833503  ],
       [0.9832713 ],
       [0.95919794],
       [0.9860243 ],
       [0.720223  ],
       [0.73776406],
       [0.9861644 ],
       [0.9950024 ],
       [0.985

In [67]:
rcl100 = avg_recall(gt100, k100pc)
rcl1k = avg_recall(gt1000, k1000pc)
rcl10k = avg_recall(gt10000, k10000pc)

In [35]:
def mae(a, b):
    return np.abs(a-b).mean()

In [59]:
k100a

array([[0.9080351 ],
       [0.01038658],
       [0.81954634],
       [0.867749  ],
       [0.9554524 ],
       [0.92206615],
       [0.96424   ],
       [0.7041061 ],
       [0.65030015],
       [0.92146146],
       [0.88862234],
       [0.5259446 ],
       [0.96557385],
       [0.56344414],
       [0.88585484],
       [0.8819937 ],
       [0.93058175],
       [0.9334532 ],
       [0.92205316],
       [0.6825808 ],
       [0.90727675],
       [0.851049  ],
       [0.57128537],
       [0.96524924],
       [0.7810821 ],
       [0.93364197],
       [0.86473143],
       [0.47193652],
       [0.95891124],
       [0.91958004],
       [0.82356715],
       [0.8778961 ],
       [0.28275743],
       [0.90700305],
       [0.1038513 ],
       [0.95844287],
       [0.6484489 ],
       [0.9339541 ],
       [0.3691302 ],
       [0.79135865],
       [0.97762257],
       [0.90009964],
       [0.8560117 ],
       [0.8713684 ],
       [0.85408735],
       [0.9266892 ],
       [0.9147195 ],
       [0.853

In [68]:
mae(rcl100, k100a[:, 0]), mae(rcl100, k100p[:, 0])

(0.06499456283109262, 0.05628413078658282)

In [69]:
mae(rcl1k, k1000a[:, 0]), mae(rcl1k, k1000p[:, 0])

(0.04483384219247847, 0.06846920840653031)

In [71]:
mae(rcl10k, k10000a[:, 0]), mae(rcl10k, k10000p[:, 0])

(0.024062065166722237, 0.07800398886650503)

In [49]:
rcl[:10], k100a[:10], k100p[:10]

(array([0.97, 0.04, 0.89, 0.95, 1.  , 0.88, 0.91, 0.7 , 0.7 , 0.93]),
 array([[0.9080351 ],
        [0.01038658],
        [0.81954634],
        [0.24774899],
        [0.9554524 ],
        [0.15206617],
        [0.18424   ],
        [0.09410609],
        [0.15030012],
        [0.92146146]], dtype=float32),
 array([[0.97714925],
        [0.04990912],
        [0.9430629 ],
        [0.8162254 ],
        [0.9943931 ],
        [0.85098034],
        [0.8063773 ],
        [0.6080246 ],
        [0.69555   ],
        [0.87039506]], dtype=float32))

In [57]:
rcl - k100a[:, 0]

array([ 6.19649005e-02,  2.96134166e-02,  7.04536581e-02,  7.02251014e-01,
        4.45476174e-02,  7.27933829e-01,  7.25760002e-01,  6.05893914e-01,
        5.49699885e-01,  8.53853703e-03,  8.11377658e-01,  2.54055401e-01,
        3.44261527e-02,  3.36555842e-01,  6.94145137e-01,  1.18006289e-01,
        6.94182515e-02,  3.65467978e-02,  3.79468417e-02,  5.07419186e-01,
        5.27232504e-02,  8.89509940e-02,  4.38714655e-01,  2.47507596e-02,
        6.38917935e-01,  6.63580298e-02,  6.35268579e-01,  4.68063473e-01,
        3.10887599e-02,  8.04199576e-02,  6.16432870e-01,  1.22103930e-01,
        2.57242559e-01, -2.70030451e-02,  1.96148697e-01,  1.15571332e-02,
        4.51551085e-01,  8.56045863e-01,  4.30869806e-01,  7.78641366e-01,
        2.23774314e-02,  5.99003649e-02,  1.13988311e-01,  5.98631622e-01,
        7.35912642e-01,  5.33107924e-02,  8.52804780e-02,  9.66767192e-02,
        1.07350111e-01,  6.86705329e-01,  4.19601730e-01,  4.27367687e-04,
        2.82725549e-02,  